{% set version = '1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bshazard
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bshazard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bshazard/bshazard_{{ version }}.tar.gz
  sha256: b14aebfb23c3397eb4f88d0726a0da9fc80dae921cb1e459a0f933c3335a12be

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-epi
    - r-survival
  run:
    - r-base
    - r-epi
    - r-survival

test:
  commands:
    - $R -e "library('bshazard')"           # [not win]
    - "\"%R%\" -e \"library('bshazard')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bshazard
  license: GPL-2.0-only
  summary: The function estimates the hazard function non parametrically from a survival object
    (possibly adjusted for covariates). The smoothed estimate is based on B-splines from
    the perspective of generalized linear mixed models. Left truncated and right
    censoring data are allowed. The package is based on the work in Rebora P (2014)
    <doi:10.32614/RJ-2014-028>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
